In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import statsmodels.api as sm
import matplotlib.pyplot as plt
import zipfile
import io

In [ ]:
articu = pd.read_csv("Articu.csv", encoding='latin1', delimiter=';')

In [ ]:
familias = pd.read_csv("FamArticu.csv", encoding='latin1', delimiter=';')

In [ ]:
articulos = pd.merge(articu, familias, on="IdArticu", how="left")

In [ ]:
articulos['FechaUltimaEntrada'] = pd.to_datetime(articulos['FechaUltimaEntrada'])
articulos['FechaCaducidad'] = pd.to_datetime(articulos['FechaCaducidad'])
articulos = articulos[articulos['FechaUltimaEntrada'] >= pd.to_datetime("2020-01-01")]

In [ ]:
valores_faltantes = articulos.isna().any().any()

if valores_faltantes:
    print("El DataFrame contiene valores nulos (NaN).")
    articulos = articulos.dropna(subset=['FechaUltimaEntrada'])


else:
    print("El DataFrame no contiene valores nulos (NaN).")

El DataFrame contiene valores nulos (NaN).

In [ ]:
ventas_dfs = []
lineas_dfs = []

for year in range(2020, 2023):
    venta_file = f"venta({year}).csv"
    lventa_file = f"lineaventa({year}).csv"

    ventas_df = pd.read_csv(venta_file, delimiter=';')
    lineas_df = pd.read_csv(lventa_file, delimiter=';')

    ventas_lineas_df = pd.merge(ventas_df, lineas_df, on="IdVenta")

    ventas_dfs.append(ventas_lineas_df)
    lineas_dfs.append(lineas_df)

ventas_lineas_total = pd.concat(ventas_dfs, ignore_index=True)

<ipython-input-17-b17c47ea551d>:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  lineas_df = pd.read_csv(lventa_file, delimiter=';')
<ipython-input-17-b17c47ea551d>:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  lineas_df = pd.read_csv(lventa_file, delimiter=';')
<ipython-input-17-b17c47ea551d>:13: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  lineas_df = pd.read_csv(lventa_file, delimiter=';')

In [ ]:
valores_faltantes = ventas_lineas_total.isna().any().any()

if valores_faltantes:
    print("El DataFrame contiene valores nulos (NaN).")
    data_articu = ventas_lineas_total.dropna()



else:
    print("El DataFrame no contiene valores nulos (NaN).")

El DataFrame no contiene valores nulos (NaN).

In [ ]:
merged_data = pd.merge(ventas_lineas_total, articulos, on="IdArticu", how="left")

In [ ]:
merged_data

,IdVenta,FechaHora,Cantidad,PVP,IdArticu,Descripcion,StockActual,FechaUltimaEntrada,FechaCaducidad,Puc,Pmc,Pvp,ProveedorHabitual,Laboratorio,IdFamilia,Familia
0,1278613,2020-01-01 08:24:03.780,1,5.31,795161,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1278614,2020-01-01 08:24:35.550,1,2.5,679426,ESPIDIFEN EFG 600 MG 20 SOBRES GRANULADO MENTA,2.0,2023-11-17,2026-06-30,1.81830,1.73,2.50,,E0611,23.0,ESP.ÊÊÊE.F.G
2,1278615,2020-01-01 08:29:43.410,1,5.18,698079,EUTIROX 112 MCG 100 COMPRIMIDOS,2.0,2023-11-13,2025-09-30,3.50075,3.50,5.18,,E0273,2.0,ESPECIALIDADES
3,1278615,2020-01-01 08:29:43.410,1,2.5,677381,ENALAPRIL CINFA 10 MG 56 COMPRIMIDOS,38.0,2023-08-25,2025-05-12,1.67200,1.25,2.50,,E0111,23.0,ESP.ÊÊÊE.F.G
4,1278615,2020-01-01 08:29:43.410,2,1.72,770065,ORFIDAL 1 MG 50 COMPR.,10.0,2023-11-20,2024-09-30,1.15995,1.16,1.72,0001,E0456,2.0,ESPECIALIDADES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048091,1696606,2022-12-31 19:52:41.420,1,12.74,688231,PRISTIQ 50 MG 28 COMPRIMIDOS LIBERACION PROLONGA,2.0,2023-11-20,2026-01-31,8.61080,8.61,12.74,0084,E0456,2.0,ESPECIALIDADES
1048092,1696617,2022-12-31 20:00:01.727,1,9.9,711186,ALMAX 500 MG 48 COMPRIMIDOS MASTICABLES,29.0,2023-09-13,2027-08-01,5.86036,5.86,10.94,,E0014,22.0,ESP.ÊÊÊE.F.P
1048093,1696622,2022-12-31 20:03:38.417,1,10.21,694761,AMOXICILINA/ACIDO CLAV CINFA EFG 875/125 30 COMP,1.0,2023-05-15,2024-12-31,3.41710,3.58,10.21,,E0111,23.0,ESP.ÊÊÊE.F.G
1048094,1696622,2022-12-31 20:03:38.417,1,2.5,662026,PARACETAMOL CINFA EFG 1 G 40 COMPRIMIDOS,74.0,2023-10-13,2024-03-31,0.83600,1.21,2.50,0001,E0111,23.0,ESP.ÊÊÊE.F.G
1048095,1696622,2022-12-31 20:03:38.417,1,1.97,754846,IBUPROFENO NORMON EFG 600 MG 40 COMPRIMIDOS RECU,49.0,2023-11-17,2024-02-01,1.31670,1.32,1.97,0001,E0426,23.0,ESP.ÊÊÊE.F.G

In [ ]:
df = pd.DataFrame(merged_data)

In [ ]:
df

,IdVenta,FechaHora,Cantidad,PVP,IdArticu,Descripcion,StockActual,FechaUltimaEntrada,FechaCaducidad,Puc,Pmc,Pvp,ProveedorHabitual,Laboratorio,IdFamilia,Familia
0,1278613,2020-01-01 08:24:03.780,1,5.31,795161,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1278614,2020-01-01 08:24:35.550,1,2.5,679426,ESPIDIFEN EFG 600 MG 20 SOBRES GRANULADO MENTA,2.0,2023-11-17,2026-06-30,1.81830,1.73,2.50,,E0611,23.0,ESP.ÊÊÊE.F.G
2,1278615,2020-01-01 08:29:43.410,1,5.18,698079,EUTIROX 112 MCG 100 COMPRIMIDOS,2.0,2023-11-13,2025-09-30,3.50075,3.50,5.18,,E0273,2.0,ESPECIALIDADES
3,1278615,2020-01-01 08:29:43.410,1,2.5,677381,ENALAPRIL CINFA 10 MG 56 COMPRIMIDOS,38.0,2023-08-25,2025-05-12,1.67200,1.25,2.50,,E0111,23.0,ESP.ÊÊÊE.F.G
4,1278615,2020-01-01 08:29:43.410,2,1.72,770065,ORFIDAL 1 MG 50 COMPR.,10.0,2023-11-20,2024-09-30,1.15995,1.16,1.72,0001,E0456,2.0,ESPECIALIDADES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048091,1696606,2022-12-31 19:52:41.420,1,12.74,688231,PRISTIQ 50 MG 28 COMPRIMIDOS LIBERACION PROLONGA,2.0,2023-11-20,2026-01-31,8.61080,8.61,12.74,0084,E0456,2.0,ESPECIALIDADES
1048092,1696617,2022-12-31 20:00:01.727,1,9.9,711186,ALMAX 500 MG 48 COMPRIMIDOS MASTICABLES,29.0,2023-09-13,2027-08-01,5.86036,5.86,10.94,,E0014,22.0,ESP.ÊÊÊE.F.P
1048093,1696622,2022-12-31 20:03:38.417,1,10.21,694761,AMOXICILINA/ACIDO CLAV CINFA EFG 875/125 30 COMP,1.0,2023-05-15,2024-12-31,3.41710,3.58,10.21,,E0111,23.0,ESP.ÊÊÊE.F.G
1048094,1696622,2022-12-31 20:03:38.417,1,2.5,662026,PARACETAMOL CINFA EFG 1 G 40 COMPRIMIDOS,74.0,2023-10-13,2024-03-31,0.83600,1.21,2.50,0001,E0111,23.0,ESP.ÊÊÊE.F.G
1048095,1696622,2022-12-31 20:03:38.417,1,1.97,754846,IBUPROFENO NORMON EFG 600 MG 40 COMPRIMIDOS RECU,49.0,2023-11-17,2024-02-01,1.31670,1.32,1.97,0001,E0426,23.0,ESP.ÊÊÊE.F.G

In [ ]:
df.to_csv('ventas.csv', index=False)

In [ ]:
ventas = pd.read_csv("ventas.csv", encoding='latin1', delimiter=',')
ventas

<ipython-input-25-2c3214b94fc8>:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  ventas = pd.read_csv("ventas.csv", encoding='latin1', delimiter=',')

,IdVenta,FechaHora,Cantidad,PVP,IdArticu,Descripcion,StockActual,FechaUltimaEntrada,FechaCaducidad,Puc,Pmc,Pvp,ProveedorHabitual,Laboratorio,IdFamilia,Familia
0,1278613,2020-01-01 08:24:03.780,1,5.31,795161,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1278614,2020-01-01 08:24:35.550,1,2.5,679426,ESPIDIFEN EFG 600 MG 20 SOBRES GRANULADO MENTA,2.0,2023-11-17,2026-06-30,1.81830,1.73,2.50,,E0611,23.0,ESP.ÃÃÃE.F.G
2,1278615,2020-01-01 08:29:43.410,1,5.18,698079,EUTIROX 112 MCG 100 COMPRIMIDOS,2.0,2023-11-13,2025-09-30,3.50075,3.50,5.18,,E0273,2.0,ESPECIALIDADES
3,1278615,2020-01-01 08:29:43.410,1,2.5,677381,ENALAPRIL CINFA 10 MG 56 COMPRIMIDOS,38.0,2023-08-25,2025-05-12,1.67200,1.25,2.50,,E0111,23.0,ESP.ÃÃÃE.F.G
4,1278615,2020-01-01 08:29:43.410,2,1.72,770065,ORFIDAL 1 MG 50 COMPR.,10.0,2023-11-20,2024-09-30,1.15995,1.16,1.72,0001,E0456,2.0,ESPECIALIDADES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048091,1696606,2022-12-31 19:52:41.420,1,12.74,688231,PRISTIQ 50 MG 28 COMPRIMIDOS LIBERACION PROLONGA,2.0,2023-11-20,2026-01-31,8.61080,8.61,12.74,0084,E0456,2.0,ESPECIALIDADES
1048092,1696617,2022-12-31 20:00:01.727,1,9.9,711186,ALMAX 500 MG 48 COMPRIMIDOS MASTICABLES,29.0,2023-09-13,2027-08-01,5.86036,5.86,10.94,,E0014,22.0,ESP.ÃÃÃE.F.P
1048093,1696622,2022-12-31 20:03:38.417,1,10.21,694761,AMOXICILINA/ACIDO CLAV CINFA EFG 875/125 30 COMP,1.0,2023-05-15,2024-12-31,3.41710,3.58,10.21,,E0111,23.0,ESP.ÃÃÃE.F.G
1048094,1696622,2022-12-31 20:03:38.417,1,2.5,662026,PARACETAMOL CINFA EFG 1 G 40 COMPRIMIDOS,74.0,2023-10-13,2024-03-31,0.83600,1.21,2.50,0001,E0111,23.0,ESP.ÃÃÃE.F.G
1048095,1696622,2022-12-31 20:03:38.417,1,1.97,754846,IBUPROFENO NORMON EFG 600 MG 40 COMPRIMIDOS RECU,49.0,2023-11-17,2024-02-01,1.31670,1.32,1.97,0001,E0426,23.0,ESP.ÃÃÃE.F.G